version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerceportfolio
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: always
    environment:
      - BACKEND_URL=localhost
      - BACKEND_PORT=8000
      - FRONTEND_URL=localhost
      - FRONTEND_PORT=3000
      - SECRET_KEY=SECRET_KEY
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=ecommerceportfolio
      - POSTGRES_SSL=disable
    ports:
      - "8000:8000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"

#  nginx:
#    build:
#      dockerfile: Dockerfile
#      context: ./nginx
#    restart: always
#    ports:
#      - "3050:80"
